<div class="text-right">
    <a class="btn btn-success" data-toggle="modal" data-target="#mdlCreate">Cadastrar certificado</a>
</div>

<br/>
<div class="panel panel-default">
    <div class="panel-heading text-center" >
        <h3 class="panel-title" >Certificados</h3>
    </div>
    <div class="panel-body text-center">
        <table class="table row" style="display:inline-table;">
            <tr>
                <th class="text-center col-md-4" >ID</th>
                <th class="text-center col-md-4" >Nome</th>
                <th class="text-center col-md-4" >Operação</th>
            </tr>
            <?php if (!empty($list_certificates->_embedded->certificate)) : ?>
                <?php foreach ($list_certificates->_embedded->certificate as $certificate): ?>
                    <tr id="element-<?=$certificate->id?>">
                        <th class="text-center"><?= $certificate->id; ?></th>
                        <th class="text-center element-name"><?= $certificate->name; ?></th>
                        <th class="text-center">
                            <a id="view-<?= $certificate->id; ?>" href="view/<?=$certificate->id?>" class="btn btn-info btn-view">
                                 <span class="glyphicon glyphicon-eye-open"></span>
                            </a>

                            <a class="btn btn-success btn-update" id="<?= $certificate->id; ?>" href="update/<?=$certificate->id?>">
                                <span class="glyphicon glyphicon-pencil" ></span>
                            </a>

                            <a class="btn btn-danger btn-delete" id="<?= $certificate->id; ?>" href="delete/<?=$certificate->id?>">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>
                        </th>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="3" class="text-center">Nenhum certificado encontrado</td>
                </tr>
            <?php endif; ?>
        </table>
    </div>
</div>


<!-- mdlCreate -->
<div class="modal fade" id="mdlCreate" tabindex="-1" role="dialog" >
    <div class="modal-dialog" role="document">
        <div class="modal-content b-r-0">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Cadastro de Certificado</h4>
            </div>
            <div class="modal-body">

                <?php $form->prepare(); // The correct enctype is set here ?>
                <?= $this->form()->openTag($form); ?>

                <?php $fileElement = $form->get('name'); ?>
                <div class="form-group">
                    <?php echo $this->formLabel($fileElement); ?>
                    <?php echo $this->formText($fileElement); ?>
                    <?php echo $this->formElementErrors($fileElement); ?>
                </div>

                <?php $fileElement = $form->get('certificate'); ?>
                <div class="form-group">
                    <?php echo $this->formLabel($fileElement); ?>
                    <?php echo $this->formFile($fileElement); ?>
                    <?php echo $this->formElementErrors($fileElement); ?>
                </div>

                <div class="text-right">
                    <a href="/" class="btn btn-danger">Cancelar</a>
                    <button type="submit" class="btn btn-success">Cadastro</button>
                </div>

                <?php echo $this->form()->closeTag(); ?>

            </div>
        </div>
    </div>
</div>
<!-- /mdlCreate -->


<!-- mdlDelete -->
<div class="modal fade" id="mdlDelete" tabindex="-1" role="dialog" >
    <div class="modal-dialog" role="document">
        <div class="modal-content b-r-0">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Excluir Cadastro</h4>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    

                    <div class="col-md-12">
                        <p>Você tem certeza disto? Esta prestes a excluir o certificado.</p>                    
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button id="btn-delete" class="btn btn-danger ladda-button" data-style="expand-left"><span class="ladda-label">Confirma</span></button>
            </div>

        </div>
    </div>
</div>
<!-- mdlDelete -->

<!-- mdlView -->
<div class="modal fade" id="mdlView" tabindex="-1" role="dialog" >
    <div class="modal-dialog" role="document">
        <div class="modal-content b-r-0">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Detalhes do certificado</h4>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    

                    <h4 class="title"></h4>
                    <p class="subject-dn">
                        
                    </p>
                    <p class="issuer-dn">
                        
                    </p>
                    <p>
                        <b>Data de validade:</b>
                        <div style="margin-left: 10px" class="note-before"> </div>
                        <div style="margin-left: 10px" class="note-after"> </div>
                    </p>

                </div>
            </div>


        </div>
    </div>
</div>
<!-- mdlView -->

<!-- mdlupdate -->
<div class="modal fade" id="mdlUpdate" tabindex="-1" role="dialog" >
    <div class="modal-dialog" role="document">
        <div class="modal-content b-r-0">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Editar Certificado</h4>
            </div>
            <div class="modal-body">

               <form id="update-form">
                            
                    <div class="form-group">
                        <label for="name">Nome</label>                    
                        <input type="text" required name="name" class="form-control" id="name-update" value="">           
                    </div>

                    <div class="form-group">
                        <label for="certificate">Certificado</label>                    
                        <input type="file" required name="certificate" class="form-control" id="certificate-update">     
                    </div>

                    <div class="text-right">
                        <a href="/" class="btn btn-danger">Cancelar</a>
                        <button type="submit" class="btn btn-success">Alterar</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<!-- /mdlupdate -->